import type { Staff } from "../domain/staff";
import { stationIdForRole } from "../domain/role";

export const DEMO_PASSWORD = "demo123";

export const DEMO_STAFF: Staff[] = [
    {
        id: "staff-selam",
        name: "Selam Bekele",
        role: "super_admin",
        pinHint: "demo123",
        email: "selam@fanaye.et",
        phone: "+251 91 123 4567",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "full_day",
        shiftHours: "08:00 AM – 06:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
        joinedDate: "2024-01-15",
    },
    {
        id: "staff-daniel",
        name: "Daniel Hailu",
        role: "owner",
        pinHint: "demo123",
        email: "daniel@fanaye.et",
        phone: "+251 91 234 5678",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "full_day",
        shiftHours: "08:00 AM – 08:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-01-20",
    },
    {
        id: "staff-hana",
        name: "Hana Tadesse",
        role: "manager",
        pinHint: "demo123",
        email: "hana@fanaye.et",
        phone: "+251 91 345 6789",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "morning",
        shiftHours: "07:00 AM – 04:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-02-01",
    },
    {
        id: "staff-sara",
        name: "Sara Mekonnen",
        role: "cashier",
        pinHint: "demo123",
        email: "sara@fanaye.et",
        phone: "+251 91 456 7890",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "morning",
        shiftHours: "07:00 AM – 03:30 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-02-10",
    },
    {
        id: "staff-karim",
        name: "Karim Tesfaye",
        role: "waiter",
        pinHint: "demo123",
        email: "karim@fanaye.et",
        phone: "+251 91 567 8901",
        active: true,
        assignedTableIds: ["table-1", "table-2", "table-3", "table-4", "table-12"],
        shiftStatus: "on_duty",
        shiftSchedule: "morning",
        shiftHours: "07:00 AM – 03:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-03-01",
    },
    {
        id: "staff-dawit",
        name: "Dawit Alemu",
        role: "waiter",
        pinHint: "demo123",
        email: "dawit@fanaye.et",
        phone: "+251 91 678 9012",
        active: true,
        assignedTableIds: ["table-5", "table-6", "table-7", "table-8"],
        shiftStatus: "on_duty",
        shiftSchedule: "evening",
        shiftHours: "03:00 PM – 11:00 PM",
        workingDays: ["Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        joinedDate: "2024-03-15",
    },
    {
        id: "staff-yonas",
        name: "Yonas Girma",
        role: "kitchen",
        stationRole: "kitchen",
        stationId: stationIdForRole("kitchen"),
        pinHint: "demo123",
        email: "yonas@fanaye.et",
        phone: "+251 91 789 0123",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "morning",
        shiftHours: "06:30 AM – 03:30 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-02-15",
    },
    {
        id: "staff-meron",
        name: "Meron Alemu",
        role: "barista",
        stationRole: "barista",
        stationId: stationIdForRole("barista"),
        pinHint: "demo123",
        email: "meron@fanaye.et",
        phone: "+251 91 890 1234",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "morning",
        shiftHours: "07:00 AM – 03:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-02-20",
    },
    {
        id: "staff-abel",
        name: "Abel Kebede",
        role: "cakes",
        stationRole: "cakes",
        stationId: stationIdForRole("cakes"),
        pinHint: "demo123",
        email: "abel@fanaye.et",
        phone: "+251 91 901 2345",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "evening",
        shiftHours: "02:00 PM – 10:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-03-05",
    },
    {
        id: "staff-liya",
        name: "Liya Mekonnen",
        role: "soft_drinks",
        stationRole: "soft_drinks",
        stationId: stationIdForRole("soft_drinks"),
        pinHint: "demo123",
        email: "liya@fanaye.et",
        phone: "+251 91 012 3456",
        active: true,
        shiftStatus: "on_duty",
        shiftSchedule: "morning",
        shiftHours: "08:00 AM – 04:00 PM",
        workingDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        joinedDate: "2024-03-10",
    },
];

export function staffById(id: string): Staff | undefined {
    return DEMO_STAFF.find(person => person.id === id);
}
